meta:
  run-mode: debug
  log-name: ./logs/console
  token: xxx
  poller-timeout: 600 # second

sqlite:
  database: database.db
  log-mode: true

redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  log-mode: true
  dial-timeout: 5  # second
  read-timeout: 3  # second
  write-timeout: 3 # second
  max-open: 60
  max-lifetime: 3600 # second
  max-idletime: 300  # second

task:
  activity-cron: 0 0/2 * * * *
  issue-cron: 0 0/10 * * * *
