meta:
  run-mode: debug
  log-path: ./logs/
  log-name: console

bot:
  token: xxx
  poller-timeout: 3600 # second

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_github_bot
  user: root
  password: 123

task:
  activity-duration: 60 # second
  issue-duration: 300 # second
