package controller

import (
	"fmt"
	"github.com/Aoi-hosizora/ahlib/xnumber"
	"github.com/Aoi-hosizora/ahlib/xstatus"
	"github.com/Aoi-hosizora/github-telebot/internal/bot/button"
	"github.com/Aoi-hosizora/github-telebot/internal/bot/fsm"
	"github.com/Aoi-hosizora/github-telebot/internal/bot/server"
	"github.com/Aoi-hosizora/github-telebot/internal/model"
	"github.com/Aoi-hosizora/github-telebot/internal/pkg/dao"
	"github.com/Aoi-hosizora/github-telebot/internal/service"
	"gopkg.in/tucnak/telebot.v2"
	"strings"
)

const (
	GITHUB_ME          = "You have bound with user '%s' without token."
	GITHUB_ME_TOKEN    = "You have bound with user '%s' with token '%s'."
	GITHUB_FAILED      = "Failed to get github information, please retry later."
	GITHUB_NOT_FOUND   = "Github user not found."
	GITHUB_EMPTY       = "Empty events: \\[]"
	GITHUB_SEND_PAGE_Q = "Please send the page you want to get, number required."
	NUM_REQUIRED       = "Excepted integer, but got a string. Please resend an integer."

	ISSUE_ONLY_FOR_TOKEN           = "This only can be allowed if you have bound with a token."
	ISSUE_ALLOW_Q                  = "Would you need to filter the message generated by yourself?"
	ISSUE_ALLOW_FILTER_SUCCESS     = "Success to allow bot to send issue events periodically (filter me)."
	ISSUE_ALLOW_NOT_FILTER_SUCCESS = "Success to allow bot to send issue events periodically (not filter me)."
	ISSUE_DISALLOW_SUCCESS         = "Success to disallow bot to send issue events periodically."
	ISSUE_ALLOW_FAILED             = "Failed to allow bot to send issue events periodically."
	ISSUE_DISALLOW_FAILED          = "Failed to disallow bot to send issue events periodically."
)

// /allowissue
func AllowIssueCtrl(m *telebot.Message) {
	user := dao.QueryUser(m.Chat.ID)
	if user == nil {
		_ = server.Bot().Reply(m, BIND_NOT_YET)
		return
	} else if user.Token == "" {
		_ = server.Bot().Reply(m, ISSUE_ONLY_FOR_TOKEN)
		return
	}

	_ = server.Bot().Reply(m, ISSUE_ALLOW_Q, &telebot.ReplyMarkup{
		InlineKeyboard: [][]telebot.InlineButton{
			{*button.InlineBtnFilter, *button.InlineBtnNotFilter}, {*button.InlineBtnCancel},
		},
	})
}

// button.InlineBtnFilter
func InlineBtnFilterCtrl(c *telebot.Callback) {
	m := c.Message
	_ = server.Bot().Delete(m)

	flag := ""
	user := dao.QueryUser(m.Chat.ID)
	if user == nil {
		flag = BIND_NOT_YET
	} else if user.Token == "" {
		flag = ISSUE_ONLY_FOR_TOKEN
	} else {
		status := dao.UpdateUserAllowIssue(user.ChatID, true, true)
		if status == xstatus.DbNotFound {
			flag = BIND_NOT_YET
		} else if status == xstatus.DbFailed {
			flag = ISSUE_ALLOW_FAILED
		} else {
			flag = ISSUE_ALLOW_FILTER_SUCCESS
		}
	}

	_ = server.Bot().Reply(m, flag)
}

// button.InlineBtnNotFilter
func InlineBtnNotFilterCtrl(c *telebot.Callback) {
	m := c.Message
	_ = server.Bot().Delete(m)

	flag := ""
	user := dao.QueryUser(m.Chat.ID)
	if user == nil {
		flag = BIND_NOT_YET
	} else if user.Token == "" {
		flag = ISSUE_ONLY_FOR_TOKEN
	} else {
		status := dao.UpdateUserAllowIssue(user.ChatID, true, false)
		if status == xstatus.DbNotFound {
			flag = BIND_NOT_YET
		} else if status == xstatus.DbFailed {
			flag = ISSUE_ALLOW_FAILED
		} else {
			flag = ISSUE_ALLOW_NOT_FILTER_SUCCESS
		}
	}

	_ = server.Bot().Reply(m, flag)
}

// /disallowissue
func DisallowIssueCtrl(m *telebot.Message) {
	user := dao.QueryUser(m.Chat.ID)
	if user == nil {
		_ = server.Bot().Reply(m, BIND_NOT_YET)
		return
	} else if user.Token == "" {
		_ = server.Bot().Reply(m, ISSUE_ONLY_FOR_TOKEN)
		return
	}

	flag := ""
	status := dao.UpdateUserAllowIssue(user.ChatID, false, user.FilterMe)
	if status == xstatus.DbNotFound {
		flag = BIND_NOT_YET
	} else if status == xstatus.DbFailed {
		flag = ISSUE_DISALLOW_FAILED
	} else {
		flag = ISSUE_DISALLOW_SUCCESS
	}

	_ = server.Bot().Reply(m, flag)
}

// /activity
func ActivityCtrl(m *telebot.Message) {
	m.Text = "1"
	FromActivityPageCtrl(m)
}

// /activitypage
func ActivityPageCtrl(m *telebot.Message) {
	server.Bot().SetStatus(m.Chat.ID, fsm.ActivityPage)
	_ = server.Bot().Reply(m, GITHUB_SEND_PAGE_Q)
}

// fsm.ActivityPage
func FromActivityPageCtrl(m *telebot.Message) {
	page, err := xnumber.Atoi(m.Text)
	if err != nil {
		_ = server.Bot().Reply(m, NUM_REQUIRED)
		return
	} else if page <= 0 {
		page = 1
	}

	flag := ""
	v2 := false
	user := dao.QueryUser(m.Chat.ID)
	if user == nil {
		flag = BIND_NOT_YET
	} else {
		if resp, err := service.GetActivityEvents(user.Username, user.Token, page); err != nil {
			flag = GITHUB_FAILED
		} else if events, err := model.UnmarshalActivityEvents(resp); err != nil {
			flag = GITHUB_FAILED
		} else if render := service.RenderActivities(events); render == "" {
			flag = GITHUB_EMPTY
		} else {
			flag = service.RenderResult(render, user.Username) + fmt.Sprintf(" \\(page %d\\)", page) // <<<
			v2 = true
		}
	}

	server.Bot().SetStatus(m.Chat.ID, fsm.None)
	if !v2 {
		_ = server.Bot().Reply(m, flag, telebot.ModeMarkdown)
	} else {
		err := server.Bot().Reply(m, flag, telebot.ModeMarkdownV2)
		if err != nil && strings.Contains(err.Error(), "must be escaped") {
			flag = strings.ReplaceAll(flag, "\\", "")
			flag += "\n\nPlease contact with the developer with the message:\n" + err.Error()
			_ = server.Bot().Reply(m, flag, telebot.ModeMarkdown)
		}
	}
}

// /issue
func IssueCtrl(m *telebot.Message) {
	m.Text = "1"
	FromIssuePageCtrl(m)
}

// /issuepage
func IssuePageCtrl(m *telebot.Message) {
	server.Bot().SetStatus(m.Chat.ID, fsm.IssuePage)
	_ = server.Bot().Reply(m, GITHUB_SEND_PAGE_Q)
}

// fsm.IssuePage
func FromIssuePageCtrl(m *telebot.Message) {
	page, err := xnumber.Atoi(m.Text)
	if err != nil {
		_ = server.Bot().Reply(m, NUM_REQUIRED)
		return
	} else if page <= 0 {
		page = 1
	}

	v2 := false
	flag := ""
	user := dao.QueryUser(m.Chat.ID)
	if user == nil {
		flag = BIND_NOT_YET
	} else if user.Token == "" {
		flag = ISSUE_ONLY_FOR_TOKEN
	} else {
		if resp, err := service.GetIssueEvents(user.Username, user.Token, page); err != nil {
			flag = GITHUB_FAILED
		} else if events, err := model.UnmarshalIssueEvents(resp); err != nil {
			flag = GITHUB_FAILED
		} else if render := service.RenderIssues(events); render == "" {
			flag = GITHUB_EMPTY
		} else {
			v2 = true
			flag = service.RenderResult(render, user.Username) + fmt.Sprintf(" \\(page %d\\)", page) // <<<
		}
	}

	server.Bot().SetStatus(m.Chat.ID, fsm.None)
	if !v2 {
		_ = server.Bot().Reply(m, flag, telebot.ModeMarkdown)
	} else {
		err := server.Bot().Reply(m, flag, telebot.ModeMarkdownV2)
		if err != nil && strings.Contains(err.Error(), "must be escaped") {
			flag = strings.ReplaceAll(flag, "\\", "")
			flag += "\n\nPlease contact with the developer with the message:\n" + err.Error()
			_ = server.Bot().Reply(m, flag, telebot.ModeMarkdown)
		}
	}
}
